name: Build astra-sm for CoreELEC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf libtool gcc make git wget xz-utils g++ patchutils lzop pkg-config

    - name: Clone astra-sm repository
      run: |
        git clone https://github.com/catalinii/astra.git
        cd astra
        git checkout <commit-or-branch> # Opcional: checkout a un commit o branch específico

    - name: Build astra-sm
      run: |
        cd astra
        ./autogen.sh
        ./configure --host=aarch64-linux --target=aarch64-linux
        make

    - name: Package as .ipk
      run: |
        cd astra
        make install DESTDIR=$PWD/install_root
        cd install_root
        tar -czvf astra-sm-coreelec.aarch64.ipk ./*

    - name: Upload .ipk Artifact
      uses: actions/upload-artifact@v3
      with:
        name: astra-sm-coreelec.aarch64.ipk
        path: ./astra/install_root/astra-sm-coreelec.aarch64.ipk

