name: Build Astra SM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git pkg-config liblua5.2-dev

      - name: Clone Astra SM
        run: git clone https://github.com/crazycat69/astra-sm.git

      - name: Build Astra SM
        run: |
          cd astra-sm
          ./autogen.sh
          ./configure --host=aarch64
          make

      - name: Create IPK Package
        run: |
          cd astra-sm
          make ipk

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: astra-sm_aarch64.ipk
          path: astra-sm/*.ipk

