name: Build Astra SM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Astra SM repository
        run: git clone https://github.com/crazycat69/astra-sm.git

      - name: Change directory to astra-sm
        run: cd astra-sm

      - name: Generate version.txt
        run: echo "version=\"$(git describe --tags)\"" > astra-sm/version.txt

      - name: Build the project
        run: |
          cd astra-sm
          ./autogen.sh
          ./configure --host=aarch64
          make

      - name: Create IPK file
        run: |
          cd astra-sm
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astra-sm_$(git describe --tags).ipk
          path: astra-sm/aarch64/astra-sm_*.ipk
